import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Raleway } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/landing-page/footer";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  fallback: ["sans-serif"],
  weight: ["600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.variable} ${raleway.className}  antialiased`}
        style={{
          fontWeight: "600",
          letterSpacing: "0.02em",
        }}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
